version: "3.5"

services:
  frontend:
    image: julian2507/helicopterproject:frontend_v4
    restart: unless-stopped
    build:
      context: "./Our-Project"
    platform: "linux/amd64"

  backend:
    image: julian2507/helicopterproject:frontend_v6
    restart: unless-stopped
    build:
      context: "./backend"
    platform: "linux/amd64"

  nginx:
    image: nginx
    ports:
      - "80:80"
