version: "3.5"

services:
  frontend:
    image: julian2507/hp:frontend_v2
    restart: unless-stopped
    build:
      context: "./Our-Project"
    platform: "linux/amd64"

  backend:
    image: julian2507/hp:backend_v3
    restart: unless-stopped
    build:
      context: "./backend"
    platform: "linux/amd64"

  nginx:
    image: nginx
    ports:
      - "80:80"
